[2025-06-13T14:10:54.184-0400] {processor.py:153} INFO - Started process (PID=97194) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:10:54.186-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:10:54.186-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:10:54.186-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:10:54.214-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:10:54.212-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:10:54.215-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:10:54.667-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 0.484 seconds
[2025-06-13T14:12:50.846-0400] {processor.py:153} INFO - Started process (PID=97747) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:12:50.848-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:12:50.848-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:12:50.848-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:12:50.882-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:12:50.880-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:12:50.882-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:12:51.360-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 0.515 seconds
[2025-06-13T14:14:38.843-0400] {processor.py:153} INFO - Started process (PID=799) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:14:38.845-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:14:38.846-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:14:38.846-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:14:38.860-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:14:38.859-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:14:38.861-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:14:39.347-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 0.504 seconds
[2025-06-13T14:16:35.993-0400] {processor.py:153} INFO - Started process (PID=3565) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:16:35.998-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:16:35.998-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:16:35.998-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:16:36.012-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:16:36.011-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:16:36.012-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:16:36.534-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 0.541 seconds
[2025-06-13T14:18:30.809-0400] {processor.py:153} INFO - Started process (PID=6333) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:18:30.812-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:18:30.812-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:18:30.812-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:18:30.827-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:18:30.826-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:18:30.828-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:18:31.293-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 0.485 seconds
[2025-06-13T14:20:36.382-0400] {processor.py:153} INFO - Started process (PID=6721) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:20:36.384-0400] {processor.py:743} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:20:36.384-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:20:36.384-0400] {dagbag.py:538} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:20:36.404-0400] {logging_mixin.py:137} INFO - [2025-06-13T14:20:36.401-0400] {dagbag.py:343} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/drift-retrainer/venv311/lib/python3.11/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:20:36.404-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:20:36.905-0400] {processor.py:175} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 0.524 seconds
[2025-06-13T14:23:20.859-0400] {processor.py:186} INFO - Started process (PID=7817) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:23:20.861-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:23:20.862-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:23:20.862-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:23:20.865-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:23:20.864-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:23:20.865-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:23:21.576-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 725.639 seconds
[2025-06-13T14:26:24.053-0400] {processor.py:186} INFO - Started process (PID=8057) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:26:24.055-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:26:24.056-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:26:24.056-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:26:24.058-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:26:24.057-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:26:24.058-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:26:24.487-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 434.621 seconds
[2025-06-13T14:29:28.038-0400] {processor.py:186} INFO - Started process (PID=8879) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:29:28.041-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:29:28.041-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:29:28.041-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:29:28.045-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:29:28.043-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:29:28.045-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:29:28.442-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 404.768 seconds
[2025-06-13T14:32:25.444-0400] {processor.py:186} INFO - Started process (PID=9517) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:32:25.446-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:32:25.446-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:32:25.446-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:32:25.449-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:32:25.448-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:32:25.449-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:32:25.871-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 428.395 seconds
[2025-06-13T14:35:30.680-0400] {processor.py:186} INFO - Started process (PID=10167) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:35:30.683-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:35:30.684-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:35:30.684-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:35:30.690-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:35:30.690-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:35:30.691-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:35:31.141-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 462.959 seconds
[2025-06-13T14:38:30.327-0400] {processor.py:186} INFO - Started process (PID=11222) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:38:30.329-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:38:30.329-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:38:30.329-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:38:30.332-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:38:30.332-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:38:30.333-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:38:30.807-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 481.636 seconds
[2025-06-13T14:41:11.324-0400] {processor.py:186} INFO - Started process (PID=11725) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:41:11.326-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:41:11.326-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:41:11.326-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:41:11.328-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:41:11.328-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:41:11.329-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:41:11.784-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 461.483 seconds
[2025-06-13T14:43:39.499-0400] {processor.py:186} INFO - Started process (PID=11973) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:43:39.501-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:43:39.501-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:43:39.501-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:43:39.503-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:43:39.503-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:43:39.503-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:43:39.763-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 265.183 seconds
[2025-06-13T14:46:04.292-0400] {processor.py:186} INFO - Started process (PID=12298) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:46:04.294-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:46:04.294-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:46:04.294-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:46:04.296-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:46:04.295-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:46:04.296-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:46:04.551-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 260.210 seconds
[2025-06-13T14:48:31.883-0400] {processor.py:186} INFO - Started process (PID=12501) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:48:31.885-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:48:31.885-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:48:31.885-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:48:31.887-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:48:31.886-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:48:31.887-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:48:32.150-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 268.667 seconds
[2025-06-13T14:50:59.569-0400] {processor.py:186} INFO - Started process (PID=12741) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:50:59.571-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:50:59.572-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:50:59.572-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:50:59.573-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:50:59.573-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:50:59.573-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:50:59.831-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 263.634 seconds
[2025-06-13T14:53:28.648-0400] {processor.py:186} INFO - Started process (PID=14089) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:53:28.650-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:53:28.651-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:53:28.651-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:53:28.652-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:53:28.652-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:53:28.653-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:53:28.915-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 268.329 seconds
[2025-06-13T14:56:03.292-0400] {processor.py:186} INFO - Started process (PID=14346) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:56:03.294-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:56:03.295-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:56:03.295-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:56:03.297-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:56:03.296-0400] {dagbag.py:387} ERROR - Failed to import: /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
Traceback (most recent call last):
  File "/Users/pranavr/.pyenv/versions/3.11.6/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-06-13T14:56:03.297-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:56:03.664-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 373.119 seconds
[2025-06-13T14:58:41.261-0400] {processor.py:186} INFO - Started process (PID=14696) to work on /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:58:41.263-0400] {processor.py:914} INFO - Processing file /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py for tasks to queue
[2025-06-13T14:58:41.263-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.263-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:58:41.269-0400] {processor.py:925} INFO - DAG(s) 'drift_detection' retrieved from /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py
[2025-06-13T14:58:41.378-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.377-0400] {override.py:1930} INFO - Created Permission View: can edit on DAG:drift_detection
[2025-06-13T14:58:41.382-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.382-0400] {override.py:1930} INFO - Created Permission View: can read on DAG:drift_detection
[2025-06-13T14:58:41.384-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.384-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG:drift_detection
[2025-06-13T14:58:41.386-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.386-0400] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:drift_detection
[2025-06-13T14:58:41.388-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.388-0400] {override.py:1930} INFO - Created Permission View: can create on DAG Run:drift_detection
[2025-06-13T14:58:41.391-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.390-0400] {override.py:1930} INFO - Created Permission View: can read on DAG Run:drift_detection
[2025-06-13T14:58:41.393-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.393-0400] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:drift_detection
[2025-06-13T14:58:41.393-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.393-0400] {dag.py:3239} INFO - Sync 1 DAGs
[2025-06-13T14:58:41.397-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.397-0400] {dag.py:3262} INFO - Creating ORM DAG for drift_detection
[2025-06-13T14:58:41.401-0400] {logging_mixin.py:190} INFO - [2025-06-13T14:58:41.401-0400] {dag.py:4180} INFO - Setting next_dagrun for drift_detection to 2025-06-13T17:00:00+00:00, run_after=2025-06-13T18:00:00+00:00
[2025-06-13T14:58:41.407-0400] {processor.py:208} INFO - Processing /Users/pranavr/drift-retrainer/dags/drfit_detection_dag.py took 148.019 seconds
